import { SyntheticWindow, SyntheticDOMImplementation } from "./window";
import { ISyntheticBrowser } from "../browser";
import { SyntheticLocation } from "../location";
import { SyntheticHTMLElement } from "./html";
import { SyntheticCSSStyleSheet } from "./css";
import { Sandbox } from "aerial-sandbox";
import { SyntheticDOMText, SyntheticDOMNode, IMarkupNodeVisitor, SyntheticDOMElement, SyntheticDOMComment, SyntheticDOMContainer, SyntheticDOMContainerEdit, syntheticElementClassType, SyntheticDocumentFragment, SyntheticDOMContainerEditor } from "./markup";
import { Mutation, ITreeWalker, MoveChildMutation, InsertChildMutation, RemoveChildMutation, ObservableCollection } from "aerial-common";
export interface IRegisterComponentOptions {
    prototype: any;
    extends: string;
}
export declare namespace SyntheticDocumentMutationTypes {
    const ADD_DOCUMENT_STYLE_SHEET_EDIT = "addDocumentStyleSheetEdit";
    const REMOVE_DOCUMENT_STYLE_SHEET_EDIT = "removeDocumentStyleSheetEdit";
    const MOVE_DOCUMENT_STYLE_SHEET_EDIT = "moveDocumentStyleSheetEdit";
}
export declare class SyntheticDocumentEdit extends SyntheticDOMContainerEdit<SyntheticDocument> {
    addStyleSheet(stylesheet: SyntheticCSSStyleSheet, index?: number): InsertChildMutation<SyntheticDocument, SyntheticCSSStyleSheet>;
    removeStyleSheet(stylesheet: SyntheticCSSStyleSheet): RemoveChildMutation<SyntheticDocument, SyntheticCSSStyleSheet>;
    moveStyleSheet(stylesheet: SyntheticCSSStyleSheet, index: number): MoveChildMutation<SyntheticDocument, SyntheticCSSStyleSheet>;
    protected addDiff(newDocument: SyntheticDocument): any;
}
export declare class SyntheticDocumentEditor<T extends SyntheticDocument> extends SyntheticDOMContainerEditor<T> {
    applySingleMutation(mutation: Mutation<T>): void;
}
export declare function isDOMDocumentMutation(mutation: Mutation<any>): boolean;
export declare class SyntheticDocument extends SyntheticDOMContainer {
    readonly defaultNamespaceURI: string;
    readonly nodeType: number;
    readonly styleSheets: ObservableCollection<SyntheticCSSStyleSheet>;
    $registeredElements: any;
    $window: SyntheticWindow;
    $ownerNode: SyntheticDOMNode;
    $implementation: SyntheticDOMImplementation;
    cookie: string;
    constructor(defaultNamespaceURI: string, implementation?: SyntheticDOMImplementation);
    readonly implementation: SyntheticDOMImplementation;
    readonly sandbox: Sandbox;
    readonly scripts: any;
    readonly browser: ISyntheticBrowser;
    readonly ownerNode: SyntheticDOMNode;
    readonly defaultView: SyntheticWindow;
    readonly documentElement: SyntheticHTMLElement;
    readonly head: SyntheticHTMLElement;
    readonly body: SyntheticHTMLElement;
    location: SyntheticLocation;
    readonly URL: string;
    open(): void;
    close(): void;
    accept(visitor: IMarkupNodeVisitor): any;
    getElementById(id: string): SyntheticDOMElement;
    createElementNS(ns: string, tagName: string): SyntheticDOMElement;
    $getElementClassNS(ns: string, tagName: string): syntheticElementClassType;
    createEdit(): SyntheticDocumentEdit;
    createElement(tagName: "a"): SyntheticHTMLElement;
    createElement(tagName: "abbr"): SyntheticHTMLElement;
    createElement(tagName: "acronym"): SyntheticHTMLElement;
    createElement(tagName: "address"): SyntheticHTMLElement;
    createElement(tagName: "applet"): SyntheticHTMLElement;
    createElement(tagName: "area"): SyntheticHTMLElement;
    createElement(tagName: "article"): SyntheticHTMLElement;
    createElement(tagName: "aside"): SyntheticHTMLElement;
    createElement(tagName: "audio"): SyntheticHTMLElement;
    createElement(tagName: "b"): SyntheticHTMLElement;
    createElement(tagName: "base"): SyntheticHTMLElement;
    createElement(tagName: "basefont"): SyntheticHTMLElement;
    createElement(tagName: "bdi"): SyntheticHTMLElement;
    createElement(tagName: "bdo"): SyntheticHTMLElement;
    createElement(tagName: "big"): SyntheticHTMLElement;
    createElement(tagName: "blockquote"): SyntheticHTMLElement;
    createElement(tagName: "body"): SyntheticHTMLElement;
    createElement(tagName: "br"): SyntheticHTMLElement;
    createElement(tagName: "button"): SyntheticHTMLElement;
    createElement(tagName: "canvas"): SyntheticHTMLElement;
    createElement(tagName: "caption"): SyntheticHTMLElement;
    createElement(tagName: "center"): SyntheticHTMLElement;
    createElement(tagName: "cite"): SyntheticHTMLElement;
    createElement(tagName: "code"): SyntheticHTMLElement;
    createElement(tagName: "col"): SyntheticHTMLElement;
    createElement(tagName: "colgroup"): SyntheticHTMLElement;
    createElement(tagName: "datalist"): SyntheticHTMLElement;
    createElement(tagName: "dd"): SyntheticHTMLElement;
    createElement(tagName: "del"): SyntheticHTMLElement;
    createElement(tagName: "details"): SyntheticHTMLElement;
    createElement(tagName: "dfn"): SyntheticHTMLElement;
    createElement(tagName: "dialog"): SyntheticHTMLElement;
    createElement(tagName: "dir"): SyntheticHTMLElement;
    createElement(tagName: "dl"): SyntheticHTMLElement;
    createElement(tagName: "dt"): SyntheticHTMLElement;
    createElement(tagName: "em"): SyntheticHTMLElement;
    createElement(tagName: "embed"): SyntheticHTMLElement;
    createElement(tagName: "fieldset"): SyntheticHTMLElement;
    createElement(tagName: "figcaption"): SyntheticHTMLElement;
    createElement(tagName: "figure"): SyntheticHTMLElement;
    createElement(tagName: "font"): SyntheticHTMLElement;
    createElement(tagName: "footer"): SyntheticHTMLElement;
    createElement(tagName: "form"): SyntheticHTMLElement;
    createElement(tagName: "frame"): SyntheticHTMLElement;
    createElement(tagName: "frameset"): SyntheticHTMLElement;
    createElement(tagName: "head"): SyntheticHTMLElement;
    createElement(tagName: "header"): SyntheticHTMLElement;
    createElement(tagName: "hr"): SyntheticHTMLElement;
    createElement(tagName: "html"): SyntheticHTMLElement;
    createElement(tagName: "i"): SyntheticHTMLElement;
    createElement(tagName: "iframe"): SyntheticHTMLElement;
    createElement(tagName: "img"): SyntheticHTMLElement;
    createElement(tagName: "input"): SyntheticHTMLElement;
    createElement(tagName: "ins"): SyntheticHTMLElement;
    createElement(tagName: "kbd"): SyntheticHTMLElement;
    createElement(tagName: "keygen"): SyntheticHTMLElement;
    createElement(tagName: "label"): SyntheticHTMLElement;
    createElement(tagName: "legend"): SyntheticHTMLElement;
    createElement(tagName: "li"): SyntheticHTMLElement;
    createElement(tagName: "link"): SyntheticHTMLElement;
    createElement(tagName: "main"): SyntheticHTMLElement;
    createElement(tagName: "map"): SyntheticHTMLElement;
    createElement(tagName: "mark"): SyntheticHTMLElement;
    createElement(tagName: "menu"): SyntheticHTMLElement;
    createElement(tagName: "WebMenuItem"): SyntheticHTMLElement;
    createElement(tagName: "meta"): SyntheticHTMLElement;
    createElement(tagName: "meter"): SyntheticHTMLElement;
    createElement(tagName: "nav"): SyntheticHTMLElement;
    createElement(tagName: "noframes"): SyntheticHTMLElement;
    createElement(tagName: "noscript"): SyntheticHTMLElement;
    createElement(tagName: "object"): SyntheticHTMLElement;
    createElement(tagName: "ol"): SyntheticHTMLElement;
    createElement(tagName: "optgroup"): SyntheticHTMLElement;
    createElement(tagName: "option"): SyntheticHTMLElement;
    createElement(tagName: "output"): SyntheticHTMLElement;
    createElement(tagName: "p"): SyntheticHTMLElement;
    createElement(tagName: "param"): SyntheticHTMLElement;
    createElement(tagName: "pre"): SyntheticHTMLElement;
    createElement(tagName: "progress"): SyntheticHTMLElement;
    createElement(tagName: "q"): SyntheticHTMLElement;
    createElement(tagName: "rp"): SyntheticHTMLElement;
    createElement(tagName: "rt"): SyntheticHTMLElement;
    createElement(tagName: "ruby"): SyntheticHTMLElement;
    createElement(tagName: "s"): SyntheticHTMLElement;
    createElement(tagName: "samp"): SyntheticHTMLElement;
    createElement(tagName: "script"): SyntheticHTMLElement;
    createElement(tagName: "section"): SyntheticHTMLElement;
    createElement(tagName: "select"): SyntheticHTMLElement;
    createElement(tagName: "small"): SyntheticHTMLElement;
    createElement(tagName: "source"): SyntheticHTMLElement;
    createElement(tagName: "span"): SyntheticHTMLElement;
    createElement(tagName: "strike"): SyntheticHTMLElement;
    createElement(tagName: "strong"): SyntheticHTMLElement;
    createElement(tagName: "style"): SyntheticHTMLElement;
    createElement(tagName: "sub"): SyntheticHTMLElement;
    createElement(tagName: "summary"): SyntheticHTMLElement;
    createElement(tagName: "sup"): SyntheticHTMLElement;
    createElement(tagName: "table"): SyntheticHTMLElement;
    createElement(tagName: "tbody"): SyntheticHTMLElement;
    createElement(tagName: "td"): SyntheticHTMLElement;
    createElement(tagName: "textarea"): SyntheticHTMLElement;
    createElement(tagName: "tfoot"): SyntheticHTMLElement;
    createElement(tagName: "th"): SyntheticHTMLElement;
    createElement(tagName: "thead"): SyntheticHTMLElement;
    createElement(tagName: "time"): SyntheticHTMLElement;
    createElement(tagName: "title"): SyntheticHTMLElement;
    createElement(tagName: "tr"): SyntheticHTMLElement;
    createElement(tagName: "track"): SyntheticHTMLElement;
    createElement(tagName: "tt"): SyntheticHTMLElement;
    createElement(tagName: "u"): SyntheticHTMLElement;
    createElement(tagName: "ul"): SyntheticHTMLElement;
    createElement(tagName: "var"): SyntheticHTMLElement;
    createElement(tagName: "video"): SyntheticHTMLElement;
    createElement(tagName: "wbr"): SyntheticHTMLElement;
    createElement(tagName: "a"): SyntheticHTMLElement;
    createElement(tagName: "abbr"): SyntheticHTMLElement;
    createElement(tagName: "acronym"): SyntheticHTMLElement;
    createElement(tagName: "address"): SyntheticHTMLElement;
    createElement(tagName: "applet"): SyntheticHTMLElement;
    createElement(tagName: "area"): SyntheticHTMLElement;
    createElement(tagName: "article"): SyntheticHTMLElement;
    createElement(tagName: "aside"): SyntheticHTMLElement;
    createElement(tagName: "audio"): SyntheticHTMLElement;
    createElement(tagName: "b"): SyntheticHTMLElement;
    createElement(tagName: "base"): SyntheticHTMLElement;
    createElement(tagName: "basefont"): SyntheticHTMLElement;
    createElement(tagName: "bdi"): SyntheticHTMLElement;
    createElement(tagName: "bdo"): SyntheticHTMLElement;
    createElement(tagName: "big"): SyntheticHTMLElement;
    createElement(tagName: "blockquote"): SyntheticHTMLElement;
    createElement(tagName: "body"): SyntheticHTMLElement;
    createElement(tagName: "br"): SyntheticHTMLElement;
    createElement(tagName: "button"): SyntheticHTMLElement;
    createElement(tagName: "canvas"): SyntheticHTMLElement;
    createElement(tagName: "caption"): SyntheticHTMLElement;
    createElement(tagName: "center"): SyntheticHTMLElement;
    createElement(tagName: "cite"): SyntheticHTMLElement;
    createElement(tagName: "code"): SyntheticHTMLElement;
    createElement(tagName: "col"): SyntheticHTMLElement;
    createElement(tagName: "colgroup"): SyntheticHTMLElement;
    createElement(tagName: "datalist"): SyntheticHTMLElement;
    createElement(tagName: "dd"): SyntheticHTMLElement;
    createElement(tagName: "del"): SyntheticHTMLElement;
    createElement(tagName: "details"): SyntheticHTMLElement;
    createElement(tagName: "dfn"): SyntheticHTMLElement;
    createElement(tagName: "dialog"): SyntheticHTMLElement;
    createElement(tagName: "dir"): SyntheticHTMLElement;
    createElement(tagName: "div"): SyntheticHTMLElement;
    createElement(tagName: "dl"): SyntheticHTMLElement;
    createElement(tagName: "dt"): SyntheticHTMLElement;
    createElement(tagName: "em"): SyntheticHTMLElement;
    createElement(tagName: "embed"): SyntheticHTMLElement;
    createElement(tagName: "fieldset"): SyntheticHTMLElement;
    createElement(tagName: "figcaption"): SyntheticHTMLElement;
    createElement(tagName: "figure"): SyntheticHTMLElement;
    createElement(tagName: "font"): SyntheticHTMLElement;
    createElement(tagName: "footer"): SyntheticHTMLElement;
    createElement(tagName: "form"): SyntheticHTMLElement;
    createElement(tagName: "frame"): SyntheticHTMLElement;
    createElement(tagName: "frameset"): SyntheticHTMLElement;
    createElement(tagName: "head"): SyntheticHTMLElement;
    createElement(tagName: "header"): SyntheticHTMLElement;
    createElement(tagName: "hr"): SyntheticHTMLElement;
    createElement(tagName: "html"): SyntheticHTMLElement;
    createElement(tagName: "i"): SyntheticHTMLElement;
    createElement(tagName: "iframe"): SyntheticHTMLElement;
    createElement(tagName: "img"): SyntheticHTMLElement;
    createElement(tagName: "input"): SyntheticHTMLElement;
    createElement(tagName: "ins"): SyntheticHTMLElement;
    createElement(tagName: "kbd"): SyntheticHTMLElement;
    createElement(tagName: "keygen"): SyntheticHTMLElement;
    createElement(tagName: "label"): SyntheticHTMLElement;
    createElement(tagName: "legend"): SyntheticHTMLElement;
    createElement(tagName: "li"): SyntheticHTMLElement;
    createElement(tagName: "link"): SyntheticHTMLElement;
    createElement(tagName: "main"): SyntheticHTMLElement;
    createElement(tagName: "map"): SyntheticHTMLElement;
    createElement(tagName: "mark"): SyntheticHTMLElement;
    createElement(tagName: "menu"): SyntheticHTMLElement;
    createElement(tagName: "WebMenuItem"): SyntheticHTMLElement;
    createElement(tagName: "meta"): SyntheticHTMLElement;
    createElement(tagName: "meter"): SyntheticHTMLElement;
    createElement(tagName: "nav"): SyntheticHTMLElement;
    createElement(tagName: "noframes"): SyntheticHTMLElement;
    createElement(tagName: "noscript"): SyntheticHTMLElement;
    createElement(tagName: "object"): SyntheticHTMLElement;
    createElement(tagName: "ol"): SyntheticHTMLElement;
    createElement(tagName: "optgroup"): SyntheticHTMLElement;
    createElement(tagName: "option"): SyntheticHTMLElement;
    createElement(tagName: "output"): SyntheticHTMLElement;
    createElement(tagName: "p"): SyntheticHTMLElement;
    createElement(tagName: "param"): SyntheticHTMLElement;
    createElement(tagName: "pre"): SyntheticHTMLElement;
    createElement(tagName: "progress"): SyntheticHTMLElement;
    createElement(tagName: "q"): SyntheticHTMLElement;
    createElement(tagName: "rp"): SyntheticHTMLElement;
    createElement(tagName: "rt"): SyntheticHTMLElement;
    createElement(tagName: "ruby"): SyntheticHTMLElement;
    createElement(tagName: "s"): SyntheticHTMLElement;
    createElement(tagName: "samp"): SyntheticHTMLElement;
    createElement(tagName: "script"): SyntheticHTMLElement;
    createElement(tagName: "section"): SyntheticHTMLElement;
    createElement(tagName: "select"): SyntheticHTMLElement;
    createElement(tagName: "small"): SyntheticHTMLElement;
    createElement(tagName: "source"): SyntheticHTMLElement;
    createElement(tagName: "span"): SyntheticHTMLElement;
    createElement(tagName: "strike"): SyntheticHTMLElement;
    createElement(tagName: "strong"): SyntheticHTMLElement;
    createElement(tagName: "style"): SyntheticHTMLElement;
    createElement(tagName: "sub"): SyntheticHTMLElement;
    createElement(tagName: "summary"): SyntheticHTMLElement;
    createElement(tagName: "sup"): SyntheticHTMLElement;
    createElement(tagName: "table"): SyntheticHTMLElement;
    createElement(tagName: "tbody"): SyntheticHTMLElement;
    createElement(tagName: "td"): SyntheticHTMLElement;
    createElement(tagName: "textarea"): SyntheticHTMLElement;
    createElement(tagName: "tfoot"): SyntheticHTMLElement;
    createElement(tagName: "th"): SyntheticHTMLElement;
    createElement(tagName: "thead"): SyntheticHTMLElement;
    createElement(tagName: "time"): SyntheticHTMLElement;
    createElement(tagName: "title"): SyntheticHTMLElement;
    createElement(tagName: "tr"): SyntheticHTMLElement;
    createElement(tagName: "track"): SyntheticHTMLElement;
    createElement(tagName: "tt"): SyntheticHTMLElement;
    createElement(tagName: "u"): SyntheticHTMLElement;
    createElement(tagName: "ul"): SyntheticHTMLElement;
    createElement(tagName: "var"): SyntheticHTMLElement;
    createElement(tagName: "video"): SyntheticHTMLElement;
    createElement(tagName: "wbr"): SyntheticHTMLElement;
    createElement(unknownTagName: any): SyntheticHTMLElement;
    registerElement(tagName: string, elementClass: syntheticElementClassType): any;
    registerElement(tagName: string, options: IRegisterComponentOptions): any;
    registerElementNS(ns: string, tagName: string, elementClass: syntheticElementClassType): any;
    registerElementNS(ns: string, tagName: string, options: IRegisterComponentOptions): any;
    createComment(nodeValue: string): SyntheticDOMComment;
    createTextNode(nodeValue: string): SyntheticDOMText;
    createDocumentFragment(): SyntheticDocumentFragment;
    visitWalker(walker: ITreeWalker): void;
    onChildAdded(child: SyntheticDOMNode, index: number): void;
    protected cloneShallow(): SyntheticDocument;
    hasFocus(): boolean;
    $linkClone(clone: SyntheticDocument): any;
    private own<T>(node);
    createEditor(): SyntheticDocumentEditor<this>;
    write(content: string): void;
    private onStyleSheetsEvent({mutation});
}
